---
title: "Visualize resurgence analysis results"
output: html_document
---

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(rcartocolor)
theme_set(theme_minimal())
# library(cowplot)
source('geoms.R')
```

```{r}
load('results/lab_trajectory_waves_standardized_by_earlyday0.Rda')
load('results/risk_prediction.Rda')
load('results/labs_observations.Rda')
```

```{r eval=FALSE, include=FALSE}
res.all.lab %>% 
  filter(setting != 'all', scale == 'original',
         setting == 'ever') %>% 
  select(- contains('CI'), - se, - total_n) %>% 
  pivot_wider(names_from = 'wave', values_from = 'mean') %>% 
  mutate(diff = abs(late - early),
         Lab = fct_reorder(Lab, diff) %>% fct_rev()) %>% 
  pivot_longer(c(early, late), names_to = 'wave', values_to = 'mean_val') %>% 
  ggplot(aes(y = mean_val, x = days_since_positive, color = Lab)) +
  geom_line(aes(linetype = wave)) + 
  facet_wrap(~ Lab) +
  scale_color_viridis_d(end = 0.9, guide = FALSE) +
  gghighlight::gghighlight(
    use_direct_label = FALSE,
    unhighlighted_params = list(size = 0.5, colour = alpha("grey", 0.4))) +
  theme(panel.grid = element_blank()) +
  NULL
```

```{r fig.height=7, fig.width=12}
labs_by_days <- res.all.lab %>% 
  filter(setting != 'all', scale == 'original') %>% 
  select(- contains('CI'), - se, - total_n) %>% 
  pivot_wider(names_from = 'wave', values_from = 'mean') %>% 
  mutate(diff = abs(late - early),
         Lab = fct_reorder(Lab, diff) %>% fct_rev()) %>% 
  pivot_longer(c(early, late), names_to = 'wave', values_to = 'mean_val') %>% 
  ggplot(aes(y = mean_val, x = days_since_positive, 
             color = setting, linetype = wave,
             group = interaction(Lab, wave, setting))) +
  geom_line(aes()) + 
  facet_wrap(~ Lab) +
  scale_color_carto_d() +
  gghighlight::gghighlight(
    use_direct_label = FALSE,
    unhighlighted_params = list(size = 0.5, colour = alpha("grey", 0.1))) +
  theme(panel.grid = element_blank()) +
  NULL
labs_by_days
ggsave('figs/lab-by-days.png', labs_by_days)
```

```{r fig.width=12}
wave_arrows <- res.wave  %>%
  mutate(setting = fct_recode(
    setting,
    'All patients' = 'all',
    'Ever-severe patients' = 'ever',
    'Never-severe patients' = 'never'
  )) %>% 
  filter(scale == 'original', days_since_positive %in% c(0, 1, 7)) %>% 
  select(- total_n) %>% 
  pivot_wider(names_from = 'wave', values_from = 'mean') %>% 
  mutate(diff = abs(late - early),
         Lab = fct_reorder(Lab, diff) %>% fct_rev()) %>% 
  {.} %>% 
  mutate(
    diff = abs(late - early),
    days_since_positive = days_since_positive %>% 
      as_factor() %>% 
      fct_recode(
        'Day 0' = '0',
        'Day 1' = '1',
        'Average days 1-7' = '7',
      ) %>% 
      fct_relevel(rev(c('Day 0', 'Day 1', 'Average days 1-7'))),
    Lab = as_factor(Lab)%>% 
      fct_reorder(diff)) %>% 
  ggplot(aes(y = Lab, fill = days_since_positive)) +
  geom_arrowbar(aes(xmin = early, x = late), 
                column_width = 0.14, head_width = 0.07,
                head_length = 0.2,
                position = position_dodge(width = 0.7)) +
  scale_fill_carto_d(guide = guide_legend(reverse = T)) +
  labs(fill = NULL,y = NULL, x = 'Mean lab value',
       title = 'Mean lab value from early wave to late wave') +
  theme(panel.grid.minor = element_blank(),
        plot.title.position = "plot",
        legend.key.height = unit(2, 'mm'),
        legend.position = c(0.93, 0.2)) +
  facet_wrap(~ setting, ncol = 3) +
  NULL

wave_arrows
ggsave('figs/wave-arrows.png', wave_arrows,
       height = 5, width = 12)
```

Labs_all is a combination of CRP+D-dimer+albumin
```{r}
risk_scores <- risk_contribution_MGB %>%
  mutate(setting = fct_recode(
    setting,
    'All patients' = 'all',
    'Ever-severe patients' = 'ever'
  ),
  wave = fct_recode(
    wave,
    'Early wave' = 'early',
    'Late wave' = 'late'
  ),
  category = fct_recode(
    category,
    'age + gender' = 'demographics:age_gender'
  )) %>%
  ggplot(aes(
    x = wave,
    y = risk,
    color = category,
    linetype = setting,
    group = interaction(category, setting)
  )) +
  geom_line() +
  scale_color_carto_d(guide = FALSE) +
  labs(
    x = NULL,
    y = 'Risk score',
    color = NULL,
    linetype = NULL
  ) +
  geom_text(data = . %>% filter(wave == 'Late wave', setting == 'All patients'),
            aes(label = category), hjust = -0.1, vjust = 0.2) +
  theme(panel.grid.minor = element_blank(),
        panel.grid.major.x = element_blank())
risk_scores
ggsave('figs/risk_score.png', risk_scores,
       height = 3, width = 6)
```

```{r include=FALSE}
# per_lab %>%
#   mutate(obs_bin = cut(
#     n_obs, 
#     breaks = c(0:15, 20, 30, max(n_obs)))) %>% 
#   group_by(lab, obs_bin) %>% 
#   summarise(both_severities = sum(both_severities), 
#             severe = sum(severe), 
#             nonsevere = sum(nonsevere), 
#             .groups = 'drop') %>% 
#   select(lab, obs_bin, both_severities, severe, nonsevere) %>% 
#   pivot_longer(c(both_severities, severe, nonsevere)) %>% 
#   mutate(name = name %>% fct_recode(
#     'All patients' = 'both_severities',
#     'Severe patients' = 'severe',
#     'Non-severe patients' = 'nonsevere'
#   )) %>% 

# lab.prop.early.all %>% 
#   ggplot(aes(x = obs_bin, fill = value, y = fct_reorder(lab, value))) + 
#   geom_tile(colour = "white", size = 0.2) +
#   geom_text(aes(label = value), colour = "white", size = 2) +
#   scale_y_discrete(expand = c(0, 0))+
#   scale_fill_gradient(low = "lightgrey", high = "darkblue") +
#   facet_wrap(~ name, nrow = 1) +
#   labs(x = 'Binned number of values a patient has for each lab',
#        y = NULL, fill = '# patients') +
#   theme(panel.grid.major = element_blank(),
#         legend.position = c(0.93, 0.2),
#         axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5),
#         axis.ticks.y = element_blank()
#   )
```

